version: '3.7'
services:
  webrtc-janus:
    build: 
      context: ./webrtc-janus
    hostname: webrtc-janus
    container_name: webrtc-janus
    volumes:
      - ./data:/opt/data
    privileged: true
    devices:
      - /dev
    ports:
      - "80:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8989:8989"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
      - "8000:8000"
    environment:
      - DOCKER_IP=${DOCKER_IP}
  gstreamer-sample:
    build: 
      context: ./gstreamer-sample
    hostname: gstreamer-sample
    container_name: gstreamer-sample
    privileged: true
    devices:
      - /dev
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "3033:3033"
      # 性能の低い端末だと、この個数のポートフォワーディングできない
      # - "59000-65000:59000-65000/udp"
    tty: true
    depends_on:
      - "webrtc-janus"
    command: >
      gst-launch-1.0 
        audiotestsrc ! 
          audioresample ! audio/x-raw,channels=1,rate=48000 ! 
          opusenc bitrate=20000 ! 
            rtpopuspay ! udpsink host=webrtc-janus port=5002 
        videotestsrc ! 
          video/x-raw,width=640,height=480,framerate=30/1 ! 
          videoconvert ! timeoverlay ! 
          vp8enc error-resilient=1 ! 
            rtpvp8pay mtu=1500 ! udpsink host=webrtc-janus port=5004
